/* @pjs preload=
"truth.PNG,
police.png,
starttorunDay1.png,
teaching1.png,
teaching2.png,
final1.png,
starttorun.png,
scream.png,
surprise.PNG,
backGround_01.png,
backGround_02.png,
backGround_03.png,
backGround_04.png,
backGround_05.png,
gamestart01.png,
gamestart02.png,
mc-01.png,
house.png,
backGround_06.png,
people1.png,
people2.png,
people3.png,
people4.png,
passerby1.png,
passerby2.png,
Screambro.png,
shock.PNG,
interview.png,
bird.png,
hear.png,
killer.png,
ghost.png
report1.png
report2.png,
wonder.PNG ";
font="JF-Dot-K12.ttf"; */
