/* @pjs preload=
"img/truth.PNG,
img/police.png,
img/starttorunDay1.png,
img/teaching1.png,
img/teaching2.png,
img/final1.png,
img/starttorun.png,
img/scream.png,
img/surprise.PNG,
img/backGround_01.png,
img/backGround_02.png,
img/backGround_03.png,
img/backGround_04.png,
img/backGround_05.png,
img/gamestart01.png,
img/gamestart02.png,
img/mc-01.png,
img/house.png,
img/backGround_06.png,
img/people1.png,
img/people2.png,
img/people3.png,
img/people4.png,
img/passerby1.png,
img/passerby2.png,
img/Screambro.png,
img/shock.PNG,
img/interview.png,
img/bird.png,
img/hear.png,
img/killer.png,
img/ghost.png
img/report1.png
img/report2.png,
img/wonder.PNG ";
font="font/JF-Dot-K12.ttf"; */
